# Generated by Django 5.1.2 on 2024-11-04 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(auto_created=True)),
                ('name', models.CharField(error_messages={'invalid': 'Enter name!!'}, max_length=100)),
                ('email', models.EmailField(error_messages={'invalid': 'This email is already used Try another email'}, max_length=254, null=True, unique=True)),
                ('department', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
